### PR TITLE
Refactor function value::equal, extract int64,uint64,double's equal to a sub function value::number_equal. Readability might be better.

### PR DESCRIPTION
**Pull request by ninghejun**
Refactor function value::equal, extract int64,uint64,double's equal to a sub function value::number_equal. Readability might be better.

### CODE REVIEW

**Comment by vinniefalco** [comment]
What problem is this trying to solve? It seems we are adding a new public function, `number_equal`, which has undefined behavior for some inputs.

**Comment by ninghejun** [comment]
> What problem is this trying to solve? It seems we are adding a new public function, `number_equal`, which has undefined behavior for some inputs.

Switch nesting in the equal function is not readable enough. This submission is an attempt to improve readability.

`number_equal` is private, only called by `equal`.  the inputs have been checked by `is_number()` in `equal`.
If we call `number_equal` separately, we get undefined behavior.  It was my fault. I can add parameter checks to the function `number_equal` later.

Is this submission worth it?

**Comment by vinniefalco** [comment]
hmm its pretty readable as it is. There are other considerations here such as code coverage, undefined behavior, And It seems that this change fails tests. Given that the code works and is already pretty understandable, I'm not sure changing it is an improvement. But thank you for taking a look.

**Comment by ninghejun** [comment]
Yes.

I saw 'Enumeration values not handled in switch' in the test result.

These test case failures can be fixed, but result in poorer branch coverage.

Then this change is meaningless.

So this pull request can be closed.

**Pull request closed without merging**
