### PR TITLE
Version 2 (Boost 1.76.0)

### PR DESCRIPTION
**Pull request by grisumbras**

### CODE REVIEW

**Comment by grisumbras** [comment]
The CI errors appear to be some Ubuntu apt problems. Can someone restart the jobs?

**Comment by vinniefalco** [comment]
Commit message should read "Update release notes"

**Comment by grisumbras** [comment]
I took the liberty of making the commit message "Create release notes" rather than "Update", because there were no release notes before that.

**Comment by grisumbras** [comment]
msvc-14.2 job decided to not run.

**Pull request merged**
