### PR TITLE
Cmake overhaul

### LINKED ISSUE #562: Refactor limits tests definition
The test is currently defined in such a way that it leads to repetition (particularly in CMake). We could refactor targets' definitions to avoid that repetition.

### LINKED ISSUE #577: The `standalone_with_boost` test fails to compile with BUILD_SHARED_LIBS=ON
Building the CMake tests (from the Boost superproject) with `BUILD_SHARED_LIBS=ON` fails with
```
[2/4] Building CXX object libs\json\test\CMakeFiles\boost_json-tests.dir\standalone_with_boost.cpp.obj
FAILED: libs/json/test/CMakeFiles/boost_json-tests.dir/standalone_with_boost.cpp.obj
C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\x64\cl.exe  /nologo /TP -DBOOST_CONTAINER_DYN_LINK -DBOOST_CONTAINER_NO_LIB -DBOOST_JSON_DYN_LINK=1 -DBOOST_JSON_NO_LIB=1 -I..\libs\json\test\. -I..\libs\json\include -I..\libs\align\include -I..\libs\assert\include -I..\libs\config\include -I..\libs\core\include -I..\libs\static_assert\include -I..\libs\container\include -I..\libs\intrusive\include -I..\libs\container_hash\include -I..\libs\detail\include -I..\libs\preprocessor\include -I..\libs\type_traits\include -I..\libs\integer\include -I..\libs\throw_exception\include -I..\libs\move\include -I..\libs\winapi\include -I..\libs\predef\include -I..\libs\exception\include -I..\libs\smart_ptr\include -I..\libs\tuple\include -I..\libs\mp11\include -I..\libs\system\include -I..\libs\utility\include -I..\libs\io\include /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /Folibs\json\test\CMakeFiles\boost_json-tests.dir\standalone_with_boost.cpp.obj /Fdlibs\json\test\CMakeFiles\boost_json-tests.dir\ /FS -c ..\libs\json\test\standalone_with_boost.cpp
C:\boost-git\develop\libs\json\include\boost/json/impl/array.ipp(30): warning C4273: 'empty_': inconsistent dll linkage
C:\boost-git\develop\libs\json\include\boost/json/array.hpp(94): note: see previous definition of 'private: static boost::json::array::table boost::json::array::empty_'
C:\boost-git\develop\libs\json\include\boost/json/impl/array.ipp(30): error C2491: 'boost::json::array::empty_': definition of dllimport static data member not allowed
C:\boost-git\develop\libs\json\include\boost/json/impl/array.ipp(39): warning C4273: 'boost::json::array::table::allocate': inconsistent dll linkage
C:\boost-git\develop\libs\json\include\boost/json/impl/array.hpp(41): note: see previous definition of 'allocate'
```
followed by many more "inconsistent dll linkage" warnings.

### LINKED ISSUE #582: Play better with superproject CML
Original take in https://github.com/boostorg/json/compare/feature%2Fcml-add-subdir

### PR DESCRIPTION
**Pull request by grisumbras**
Some refactoring of root and test CMakeLists.txt 

* Add json tests to tests target (as has been requested by @pdimov in #581) 
* Refactor json usage requirements into a separate CMake target (fixes #562)
* Overhaul of dealing with CMake use cases (fixes #582)
* Fix test standalone_with_boost for CMake (fixes #577)
* Other minor changes

### CODE REVIEW

**Comment by vinniefalco** [comment]
This will need to be squashed down before merge

**Comment by pdimov** [comment]
I'm not a fan of using fake targets, this pollutes installation.

**Comment by vinniefalco** [comment]
Which one is the fake target?

**Comment by grisumbras** [comment]
> Which one is the fake target?

`json_private`. In actuality it is a header-only version of JSON, but Peter is probably correct that users that use build systems don't need a header-only target.

 I had another Idea: setup properties via a function. E.g.
```
# CMakelists.txt
function(json_setup_properties target)
...
endfunction()

json_setup_properties(boost_json)

# test/CMakelists.txt

json_setup_properties(boost_json-limits)
json_setup_properties(boost_json-standalone_with_boost)
```

**Pull request merged**
