### PR TITLE
Fix (lack of) building without C++11 support

### PR DESCRIPTION
**Pull request by grisumbras**

### CODE REVIEW

**Comment by grisumbras** [comment]
This should fix Boost builds without C++11 support

**Comment by vinniefalco** [comment]
Suggested commit message: "Builds prior to C++11 are no-ops"

**Comment by grisumbras** [comment]
Do you think there's a need for CI test for no-op build with cxxstd=03?

**Comment by vinniefalco** [comment]
Please change "Adds back GCC 4.8 support" to "gcc-4.8 is supported"

**Comment by vinniefalco** [comment]
> Do you think there's a need for CI test for no-op build with cxxstd=03?

Up to you

**Comment by vinniefalco** [comment]
Can we please change the commit message to "gcc-4.8 is supported" ? Use an interactive rebase (`git rebase -i`) then force-push the branch.

**Comment by grisumbras** [comment]
Which commit?

**Comment by vinniefalco** [comment]
This one: 
image

**Pull request closed without merging**
