### PR TITLE
Add Mp11 to the list of dependencies in CML

### LINKED ISSUE #555: Missing CMake dependency
https://travis-ci.org/github/boostorg/boost/jobs/769225032#L1226
```
Scanning dependencies of target boost_json
[ 31%] Building CXX object libs/json/CMakeFiles/boost_json.dir/src/src.cpp.o
In file included from /home/travis/build/boostorg/boost/libs/json/include/boost/json/detail/value_to.hpp:16:0,
                 from /home/travis/build/boostorg/boost/libs/json/include/boost/json/value_to.hpp:16,
                 from /home/travis/build/boostorg/boost/libs/json/include/boost/json.hpp:40,
                 from /home/travis/build/boostorg/boost/libs/json/include/boost/json/src.hpp:27,
                 from /home/travis/build/boostorg/boost/libs/json/src/src.cpp:10:
/home/travis/build/boostorg/boost/libs/json/include/boost/json/detail/index_sequence.hpp:15:44: fatal error: boost/mp11/integer_sequence.hpp: No such file or directory
```
Likely caused by `Boost::mp11` missing in the list of dependencies here: https://github.com/boostorg/json/blob/aae1863def3fb605d77ebbefc851cc26ac1758a9/CMakeLists.txt#L80-L89

`boostdep --cmake json` says
```
target_link_libraries(boost_json
  PUBLIC
    Boost::align
    Boost::assert
    Boost::config
    Boost::container
    Boost::exception
    Boost::mp11
    Boost::system
    Boost::throw_exception
    Boost::utility
)
```

### LINKED ISSUE #558: cmake-in-superproject CI jobs
Some CI configurations should test cmake-in-superproject

### PR DESCRIPTION
**Pull request by grisumbras**
Fix #555 

Also, add tests for CMake build inside superproject (which relies on that dependency). Fix #558

### CODE REVIEW

**Comment by vinniefalco** [comment]
Commit message should read "depend on mp11"

**Comment by vinniefalco** [comment]
Great

**Comment by sdarwin** [comment]
@grisumbras 

```
chmod 755 .drone/cmake-superproject-script.sh
```

**Comment by grisumbras** [comment]
Do we need any other CMake superproject tests? @pdimov @vinniefalco

**Pull request merged**
