### PR TITLE
fix parsing for some doubles

### LINKED ISSUE #484: Parsing issue
Hello,

I'm trying to port my application ([Yadoms](https://github.com/Yadoms/yadoms)) which use rapidjson, to your new boost::json

I find a parsing issue when writing my unit tests.

I try to parse a decimal value (18.4 from my input string) and then retreive value as double.

My sample code

```c++
      const std::string data("{"
         "\"DecimalParameter\": 18.4"
         "}");

      auto& jv = boost::json::parse(data);
      boost::json::value *decimal = jv.get_object().if_contains("DecimalParameter");
      if (decimal)
      {
         BOOST_CHECK_EQUAL(decimal->as_double(), 18.4);
         BOOST_CHECK_EQUAL(decimal->get_double(), 18.4);
         BOOST_CHECK_EQUAL(decimal->to_number<double>(), 18.4);
         BOOST_CHECK_EQUAL(decimal->to_number<float>(), 18.4f);
      }
```

The results:

```
  Message: 
    check decimal->as_double() == 18.4 has failed [18.400000000000002 != 18.399999999999999]
    check decimal->get_double() == 18.4 has failed [18.400000000000002 != 18.399999999999999]
    check decimal->to_number<double>() == 18.4 has failed [18.400000000000002 != 18.399999999999999
```

The parsing is not exact, but works with floats!

Environnement:
 * boost : 1.75.0
 * VisualStudio 2019 16.8.3
 * build configuration x86

I mention also @sgallou (other main developer of Yadoms)

### PR DESCRIPTION
**Pull request by grisumbras**
Fixes #484

### CODE REVIEW

**Comment by vinniefalco** [comment]
Can we please not include whitespace changes? If you want to do this, do it in one big commit that does all the sources at once.

**Comment by grisumbras** [comment]
Sorry, my editor is configured to remove trailing whitespace. I will remove ws changes.

**Comment by vinniefalco** [comment]
I don't mind the whitespace changes if they are separated into their own commit

**Comment by vinniefalco** [comment]
This looks better, should we merge it?

**Comment by grisumbras** [comment]
It looks like it negatively affects performance. I want to look into integrating Lemire's algorithm first.

**Pull request closed without merging**
